// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwtounfssbmjzqbehyge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dG91bmZzc2JtanpxYmVoeWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjg4ODgsImV4cCI6MjA1ODcwNDg4OH0.dZWL5dCCQHsvcCvWXRnD2c5YgXjnWHtFY5WeKDvZ-zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);